# Generated by Django 3.2.15 on 2022-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
