# Generated by Django 3.2.15 on 2022-08-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.TextField(default='apple'),
        ),
    ]
