# Generated by Django 3.2.15 on 2022-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220827_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_TRANSIT', 'IN TRANSIT'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=20),
        ),
    ]
