# Generated by Django 3.2.15 on 2022-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
