# Generated by Django 3.2.15 on 2022-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating_text',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
